kind: service
apiVersion: v1
metadata:
  name: service-pod-lb
spec:
  type: LoadBalencer
  selector:
    name: nginx
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service port
    containerPort: 80 #target port
    nodePort: 32761 #NODE WILL OPEN THIS PORT